# Generated by Django 3.2.5 on 2021-09-01 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_text', models.CharField(max_length=256)),
                ('p_like', models.IntegerField(default=0)),
                ('p_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_p', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_l', to='network.posts')),
                ('l_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_l', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_text', models.CharField(max_length=128)),
                ('c_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_c', to='network.posts')),
                ('c_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_c', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
