# Generated by Django 3.2.5 on 2021-09-03 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_like_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='p_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
