# Generated by Django 3.2.5 on 2021-09-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_p_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='p_username',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
