# Generated by Django 3.2.5 on 2021-09-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210915_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
